name: Robot + Browser

on: 
  workflow_dispatch:
    inputs:
      headless-mode:
          type: boolean
          description: Will it be in headless mode or not (beeter to be in headless)?
      browser:
         type: choice
         description: Which brouser should be used?
         options:
         - chromium
         - firefox
         - webkit

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pull project
      uses: actions/checkout@v3

    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.6'

    - name: Setup Robot Framework
      run: python -m pip install robotframework

    - name: Install and configure browser library
      run: python -m pip install robotframework-browser && rfbrowser init

    - name: Launch Tests
      run: ls -a && robot -v BROWSER_TYPE:${{ inputs.choice }} all_tests

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: /Users/runner/work/robot/robot/log.html
