name: Selenoid tests

on: [workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Pull project
      uses: actions/checkout@v3

    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.6'

    - name: Setup Robot Framework
      run: python -m pip install robotframework

    - name: Check Robot version
      run: robot --version

    - name: Install and configure browser library
      run: python -m pip install robotframework-browser && rfbrowser init

    - name: Launch Tests
      run: robot all_tests