name: Robot + Browser

on:
  workflow_dispatch:
    inputs:
      headless-mode:
          type: boolean
          description: Will it be in headless mode or not (better to be in headless)?
          default: true
      browser:
         type: choice
         description: Which browser should be used?
         options:
         - chromium
         - firefox
         - webkit

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - name: Pull project
      uses: actions/checkout@v3

    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.0'

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
          node-version: 20
    - run: |
          npm install -g ts-node
          npm install -D @playwright/test@latest
          npx playwright install
          npx playwright install-deps
          npx playwright --version
    - name: Install Python dependencies
      run: |
          python3 -m pip install --upgrade pip
          pip install robotframework-requests robotframework-browser robotframework-jsonlibrary pyotp fpdf Pillow pypdf ftfy
          python3 -m Browser.entry init

    - name: Launch Tests For Workflow Dispatch
      working-directory: ./all_tests
      if: github.event_name == 'workflow_dispatch'
      env:
          mode_var: ${{ inputs.headless-mode }}
          USERNAME_SECURE_VAR: ${{ secrets.USERNAME_SECURE }}
          PASSWORD_SECURE_VAR: ${{ secrets.PASSWORD_SECURE }}
      run: ls -a && robot -v USERNAME_SECURE:${{ env.USERNAME_SECURE_VAR }} -v PASSWORD_SECURE:${{ env.PASSWORD_SECURE_VAR }} -v HEAD_MODE:${{ env.mode_var }} -v BROWSER_TYPE:${{ inputs.browser }} third.robot

    - name: Launch Tests For Non Workflow Dispatch
      working-directory: ./all_tests
      if: github.event_name != 'workflow_dispatch'
      env:
          USERNAME_SECURE_VAR: ${{ secrets.USERNAME_SECURE }}
          PASSWORD_SECURE_VAR: ${{ secrets.PASSWORD_SECURE }}
      run: ls -a && robot -v USERNAME_SECURE:${{ env.USERNAME_SECURE_VAR }} -v PASSWORD_SECURE:${{ env.PASSWORD_SECURE_VAR }} -v HEAD_MODE:true -v BROWSER_TYPE:chromium third.robot

    - name: Check directory
      if: always()
      run: cd all_tests && ls -a && pwd

    - name: Move log file to /docs-directory if exists
      if: always()
      run: |
        if [ -f "./all_tests/log.html" ]; then
          echo "File exists"
          mv ./all_tests/log.html ./docs
        else
          echo "File does not exist"
        fi

    - name: Commit result of the test run
      if: always()
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Automated Changes From Github Actions
        file_pattern: './docs/log.html'
    
    # - name: Archive code coverage results
    #   uses: actions/upload-artifact@v2
    #   if: always()
    #   with:
    #     name: code-coverage-report
    #     path: |
    #       ./all_tests/log.html
    #       ./all_tests/report.html
    #       ./all_tests/output.xml
